services:
  db:
    image: postgres:18
    container_name: loyalty-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loyalty
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql   # <-- parent path for 18+
